version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeTest19094
  gitServerName: testEdgeProjects
  gitUrl: https://github.com/rlakshitha0912/EdgeTest19094
  gitUsername: rlakshitha0912
  gitToken: edge.scaffolding.EdgeTest19094.testEdgeProjects.gitToken
  gitBranch: main
